### ISSUE TITLE
Facebook connect doesn't work - uninitialized constant Firebase::FBSession (NameError)

### ISSUE THREAD

**Issue by holgersindbaek** [colinta/motion-firebase#11]
I'm trying to connect with Facebook, but I keep getting this error:

    2015-01-24 23:27:10.775 Slang[10964:1231976] firebase_facebook_helper.rb:12:in `open_facebook_session:': uninitialized constant Firebase::FBSession (NameError)
      from connect_view.rb:28:in `connect_button_tapped'
      from connect_view.rb:17:in `block in init'
      from uicontrol.rb:91:in `call:event:'
    2015-01-24 23:27:10.783 Slang[10964:1231976] *** Terminating app due to uncaught exception 'NameError', reason: 'firebase_facebook_helper.rb:12:in `open_facebook_session:': uninitialized constant Firebase::FBSession (NameError)
      from connect_view.rb:28:in `connect_button_tapped'
      from connect_view.rb:17:in `block in init'
      from uicontrol.rb:91:in `call:event:'

This is my code:

      $firebase = Firebase.new("https://slangtest.firebaseio.com")
      $firebase.open_facebook_session(permissions: ['public_profile'], allow_login_ui: true) do |error, auth_data|
        ap "error: #{error}"
        ap "auth_data: #{auth_data}"
      end

Am I doing anything wrong here?

**Comment by holgersindbaek** [comment]
Seems like I had forgotten the to include the Facebook SDK. Now I get this error though:

    Objective-C stub for message `openActiveSessionWithReadPermissions:allowLoginUI:completionHandler:' type `B@:@B@?' not precompiled. Make sure you properly link with the framework or library that defines this message.

Any suggestions on what that could be about?

**Comment by holgersindbaek** [comment]
I'm not sure how to integrate Facebook login. Can you point me in the right direction? Do I need to include the Facebook SDK separate from this gem? Can you give an example of how you'd do the "open_facebook_session"?!

**Comment by colinta** [comment]
That objective c message error usually means that the RubyMotion compiler doesn't know how to "translate" that method call. It might work if you include in your code (not somewhere that is ever executed, just in a dummy method) a call to that method.

**Comment by holgersindbaek** [comment]
I’m not sure what you mean. Can you give a quick example?

--  

All the best

Holger Sindbaek · UI/UX Designer & Web/iOS Programmer · HolgerSindbaek.com (http://holgersindbaek.com/)

Founder of Uninkd · iOS Publishing for Content Creators · Uninkd.com (http://uninkd.com/)

**Comment by colinta** [comment]
From MotionKit:

```ruby
class DummyView < UIView
private
  def dummy
    setFrame(nil)
```

**Comment by holgersindbaek** [comment]
Huh... what has that code got to do with connecting with Facebook through Firebase?

**Comment by colinta** [comment]
Like I said, this objc error:

> Objective-C stub for message `openActiveSessionWithReadPermissions:allowLoginUI:completionHandler:' type `B@:@B@?' not precompiled. Make sure you properly link with the framework or library that defines this message.

*usually* means you need to tell the rubymotion compiler to look for this method in your bridgesupport files by including it somewhere (lit. *anywhere*) in your code.

```ruby
class AnythingDoesntMatter
  def any_method_just_needs_to_be_compiled
    openActiveSessionWithReadPermissions(nil, allowLoginUI: nil, completionHandler: nil)
  end
end
```

Other possibilities: are you including the FacebookSDK (`vendor/FacebookSDK`)?  Did you follow Firebase's guide? https://www.firebase.com/docs/ios/guide/login/facebook.html

This error you're seeing doesn't seem to be the result of a motion-firebase bug (and this is not a "free support" channel, I don't have time to offer that).

**Comment by colinta** [comment]
Sorry if I sound upset in the previous message, I've got a million things going on this weekend, and just won't have time to help out on this any time soon. I think you're close, though!

**Comment by holgersindbaek** [comment]
No problem. I understand. I've ended up using the "original" method from the FacebookSDK instead. Still seems weird to me, that you should have to include method as an empty dummy method.

Good luck with the million things.

**Comment by colinta** [comment]
It is a little weird, but it's a common issue writing RubyMotion apps, so keep it in mind anytime you get that objective-c-method error.  It's usually as simple as that - adding the 'dummy' method.

(other times you need it: using `send` to call a method that you otherwise don't call in your code - that's why motion-kit and teacup need "dummy" methods)
