### ISSUE TITLE
Getting error when trying to connect to Twitter: NSURLErrorDomain error -1012

### ISSUE THREAD

**Issue by holgersindbaek** [colinta/motion-firebase#12]
It seems to be happening in the "request_twitter_credentials" method, where I'm also getting these two errors:

    Invalid parameter type
    Request error: The operation couldn’t be completed. (NSURLErrorDomain error -1012.)

This is the full error I'm getting in the terminal:

    "error: #<NSURLError:0x1791a80, description=\"The operation couldn’t be completed. (NSURLErrorDomain error -1012.)\", code=-1012, domain=\"NSURLErrorDomain\", userInfo={\"NSErrorFailingURLKey\"=>#<NSURL:0x5f43e40, URL=\"https://api.twitter.com/oauth/access_token\">, \"NSErrorFailingURLStringKey\"=>\"https://api.twitter.com/oauth/access_token\", \"NSUnderlyingError\"=>#<__NSCFError:0x48a6d80, description=\"The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1012.)\", code=-1012, domain=\"kCFErrorDomainCFNetwork\", userInfo={\"_kCFURLErrorAuthFailedResponseKey\"=>#<__NSCFType:0x5f0dce0>}>}>"

Any ideas what this could be about?

**Comment by holgersindbaek** [comment]
Found the error... line 112:

    request_token = json['auth']

Should be:

    request_token = json['oauth']

Json has no auth parameter. It only has an oauth parameter.

**Comment by colinta** [comment]
Awesome!  Submit a PR!  :-D

**Comment by colinta** [comment]
@holgersindbaek Can you submit a pull request, so that other people can benefit from your solution?

**Comment by holgersindbaek** [comment]
I’ll see if I can get to it in the weekend.

--  

All the best

Holger Sindbaek · UI/UX Designer & Web/iOS Programmer · HolgerSindbaek.com (http://holgersindbaek.com/)

Founder of Uninkd · iOS Publishing for Content Creators · Uninkd.com (http://uninkd.com/)

**Comment by colinta** [comment]
Nah nevermind I'll do it myself.  You can edit it from Github, btw, the whole process takes about 5 minutes.

**Comment by colinta** [comment]
Done, pushed to rubygems.  Available in 3.1.3.  In the future, please create a pull request instead of just sharing the solution.
