### ISSUE TITLE
Version 2.2.0 ?

### ISSUE THREAD

**Issue by dubcanada** [colinta/motion-firebase#13]
The current version is 6 versions behind, including several new features, a bunch of bug fixes, and a bunch of changes.

**Comment by colinta** [comment]
It's easy to update the framework stored in the vendor folder, and I'll try to update it soon. In the meantime, if welcome a PR! I could always use some help.

**Comment by markrickert** [comment]
This should be closed. Firebase SDK is at 2.2.1

**Comment by colinta** [comment]
Ah right - motion-firebase v3.1.4 includes firebase 2.2.1.
