### ISSUE TITLE
createUserWithEmail

### ISSUE THREAD

**Issue by Pick6Solutions** [colinta/motion-firebase#17]
Receive the following error:
undefined method `createUserWithEmail:password:withCompletionBlock:' for #<Firebase:0x116301020> (NoMethodError)

Here is my sign_in method:
```ruby
def sign_in
    f = Firebase.new
    user_email = @email.text
    user_password = @password.text
    credentials = {email: user_password, password: user_password}
    f.create_user_and_login(credentials) { |error, auth_data| }
 end
```
I've also tried simply calling `Firebase.create_user(email: email, password: password) {|error, auth_data|}` and am still receiving the same error.

Is there something I'm missing?

Thanks.

**Comment by colinta** [comment]
Oh, looks like they changed this method name!  One sec.

**Comment by MOPineyro** [comment]
I'm the original poster.

Thank you for that quick patch. You're awesome.
