### ISSUE TITLE
Getting once a query

### ISSUE THREAD

**Issue by soyoh** [colinta/motion-firebase#22]
Hi,
Is it possible to fire a query only once?
lets say, i want to query if something exist, else, create, but only fire it one, i dont want to create an observer on it.

for instance:

```
firebase = Firebase.new(...)
firebase.query(equal_to: 'group_1_3102', child: 'group_id', on: :value)
firebase.once(:value) { |snapshot|
    mp snapshot.value
}
```

For some reason the code above is ignoring the `query` and filter, and is returning all the results.
I want to filter if a group already exist, other whise create it inside the "once".

Maybe i'm doing something wrong?? and `.once` cannot be used here, and i should stop manually the observer, or smthing.

Any hint appreciated.
Thanks!!!

**Comment by colinta** [comment]
At a minimum, I think you need to be using the return value of `firebase.query`. It doesn't modify the object, IIRC.

**Comment by soyoh** [comment]
Thanks @colinta !
I checked the source code, `firebase.query` creates a `observeEventType` if a block is provided, in this case i only need to fire once the query.

what i did was to change the code there to something like

```
if block
  if options[:once]
    event_type = options.fetch(:once, FEventTypeValue)
    event_type = Firebase.convert_event_type(event_type)
    return fb_query.observeSingleEventOfType(event_type, withBlock: block)
  else
    event_type = options.fetch(:on, FEventTypeValue)
    event_type = Firebase.convert_event_type(event_type)
    return fb_query.observeEventType(event_type, withBlock: block)
  end
else
```

now instead of using `on:` i'll use `once:`
i'm pretty new to ruby, but if you find this usefull, i can do a PR.

Cheers.

**Comment by colinta** [comment]
That looks great! Yeah please submit a PR. 

The use of 'fetch' is kind of odd, only because you're providing a default value, even though the 'if' check above has ensured there *is* a value in there. 

And please add a note to the readme when you make this change!

Thanks!
M

**Comment by colinta** [comment]
Your issue got resolved, yeah?  (please close this issue if it's working for you)
